import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../models/call_analysis.dart';
import '../services/audio_service.dart';
import '../widgets/analysis_card.dart';
import '../widgets/risk_meter.dart';
import '../widgets/voice_status.dart';
import '../widgets/warning_card.dart';

class RiskScreen extends StatefulWidget {
  final CallAnalysis analysis;

  const RiskScreen({
    super.key,
    required this.analysis,
  });

  @override
  State<RiskScreen> createState() => _RiskScreenState();
}

class _RiskScreenState extends State<RiskScreen> {
  final AudioStreamService _audioService = AudioStreamService();
  late List<bool> _checkedRecommendations;
  bool _isReported = false;

  @override
  void initState() {
    super.initState();
    _checkedRecommendations = List.generate(widget.analysis.recommendations.length, (i) => false);
    _isReported = _audioService.isNumberReported(widget.analysis.callerNumber);
  }

  String _formatDuration(int seconds) {
    final mins = (seconds ~/ 60).toString().padLeft(2, '0');
    final secs = (seconds % 60).toString().padLeft(2, '0');
    return '$mins:$secs';
  }

  void _exportSecurityReport() {
    final report = '''
==================================================
🛡️ VOXSHIELD SECURITY INCIDENT AUDIT REPORT
==================================================
Caller: ${widget.analysis.callerName} (${widget.analysis.callerNumber})
Risk Level: ${widget.analysis.level.label} (${widget.analysis.overallRisk}/100)
Deepfake Score: ${widget.analysis.voiceRisk}%
Scam Intent Score: ${widget.analysis.scamRisk}%
Urgency Score: ${widget.analysis.urgencyScore}%
Voice Biometrics: ${widget.analysis.voiceAnalysis.voiceProfile} (Confidence: ${(widget.analysis.voiceAnalysis.confidence * 100).toInt()}%)

Flagged Warnings:
${widget.analysis.warnings.map((w) => '- ${w.title}: ${w.description}').join('\n')}

Transcript:
"${widget.analysis.transcript}"

Recommendations:
${widget.analysis.recommendations.map((r) => '- $r').join('\n')}
==================================================
Generated by VoxShield Real-Time Call Protection
''';

    Clipboard.setData(ClipboardData(text: report));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('📋 Incident audit report copied to clipboard.'),
        backgroundColor: Color(0xFF10B981),
      ),
    );
  }

  void _openReportNumberDialog() {
    String selectedReason = 'OTP Credential Theft';

    showDialog(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setReportState) {
            return AlertDialog(
              backgroundColor: const Color(0xFF0F172A),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
                side: const BorderSide(color: Color(0xFF334155)),
              ),
              title: const Row(
                children: [
                  Icon(Icons.report_gmailerrorred_rounded, color: Color(0xFFEF4444)),
                  SizedBox(width: 8),
                  Text('Report Malicious Caller', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),
                ],
              ),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Reporting ${widget.analysis.callerNumber} to the Telecom Scam Registry.',
                    style: const TextStyle(color: Colors.white70, fontSize: 13),
                  ),
                  const SizedBox(height: 14),
                  const Text('PRIMARY REASON', style: TextStyle(color: Colors.white60, fontSize: 11, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 6),
                  DropdownButtonFormField<String>(
                    initialValue: selectedReason,
                    dropdownColor: const Color(0xFF1E293B),
                    style: const TextStyle(color: Colors.white),
                    decoration: InputDecoration(
                      filled: true,
                      fillColor: const Color(0xFF1E293B),
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: BorderSide.none),
                    ),
                    items: const [
                      DropdownMenuItem(value: 'OTP Credential Theft', child: Text('OTP Credential Theft')),
                      DropdownMenuItem(value: 'AI Deepfake Voice Impersonation', child: Text('AI Deepfake Voice Clone')),
                      DropdownMenuItem(value: 'Bank Impersonation Fraud', child: Text('Bank Impersonation Fraud')),
                      DropdownMenuItem(value: 'Urgent Wire Demands', child: Text('Urgent Wire Demands')),
                    ],
                    onChanged: (val) {
                      if (val != null) setReportState(() => selectedReason = val);
                    },
                  ),
                ],
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context),
                  child: const Text('Cancel', style: TextStyle(color: Colors.white60)),
                ),
                ElevatedButton(
                  onPressed: () {
                    Navigator.pop(context);
                    _audioService.reportNumber(widget.analysis.callerNumber);
                    setState(() {
                      _isReported = true;
                    });
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('🚨 ${widget.analysis.callerNumber} reported as $selectedReason.'),
                        backgroundColor: const Color(0xFFEF4444),
                      ),
                    );
                  },
                  style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFFEF4444)),
                  child: const Text('Submit Report', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                ),
              ],
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final level = widget.analysis.level;

    return Scaffold(
      backgroundColor: const Color(0xFF0A0F1D),
      appBar: AppBar(
        backgroundColor: const Color(0xFF0F172A),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: Colors.white, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Call Security Audit',
          style: TextStyle(
            color: Colors.white,
            fontSize: 18,
            fontWeight: FontWeight.w800,
            letterSpacing: 0.5,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined, color: Colors.white70),
            onPressed: _exportSecurityReport,
            tooltip: 'Export Report',
          ),
        ],
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Caller summary header badge
            _buildCallHeaderCard(),
            const SizedBox(height: 18),

            // Big Centered Risk Gauge
            Center(
              child: Container(
                padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
                decoration: BoxDecoration(
                  color: const Color(0xFF131B2E),
                  borderRadius: BorderRadius.circular(24),
                  border: Border.all(color: level.color.withValues(alpha: 0.3), width: 1.5),
                  boxShadow: [
                    BoxShadow(
                      color: level.color.withValues(alpha: 0.12),
                      blurRadius: 20,
                      spreadRadius: 2,
                    ),
                  ],
                ),
                child: Column(
                  children: [
                    RiskMeter(
                      score: widget.analysis.overallRisk,
                      level: widget.analysis.level,
                      size: 190,
                      subtitle: 'Comprehensive Multimodal AI Evaluation',
                    ),
                    const SizedBox(height: 12),
                    Text(
                      widget.analysis.level == RiskLevel.safe
                          ? 'This call exhibited standard conversational acoustics and no deceptive intent.'
                          : 'High probability of social engineering, identity deception, or credential harvesting.',
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        color: Colors.white70,
                        fontSize: 13,
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Detection Breakdown Metrics Card
            const Text(
              'RISK BREAKDOWN',
              style: TextStyle(
                color: Colors.white60,
                fontSize: 12,
                fontWeight: FontWeight.w800,
                letterSpacing: 1.2,
              ),
            ),
            const SizedBox(height: 8),
            AnalysisCard(
              deepfakeScore: widget.analysis.voiceRisk,
              scamScore: widget.analysis.scamRisk,
              urgencyScore: widget.analysis.urgencyScore,
              isCompact: false,
            ),
            const SizedBox(height: 16),

            // Voice Biometrics Widget
            VoiceStatusWidget(
              voiceAnalysis: widget.analysis.voiceAnalysis,
              isLive: false,
            ),
            const SizedBox(height: 20),

            // Flagged Warnings & Critical Threats
            if (widget.analysis.warnings.isNotEmpty) ...[
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text(
                    'DETECTED THREAT INDICATORS',
                    style: TextStyle(
                      color: Colors.white60,
                      fontSize: 12,
                      fontWeight: FontWeight.w800,
                      letterSpacing: 1.2,
                    ),
                  ),
                  Text(
                    '${widget.analysis.warnings.length} FLAGGED',
                    style: TextStyle(
                      color: level.color,
                      fontSize: 11,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              ...widget.analysis.warnings.map((w) => WarningCard(warning: w)),
              const SizedBox(height: 20),
            ],

            // Risk Progression Timeline
            if (widget.analysis.timeline.isNotEmpty) ...[
              const Text(
                'CALL RISK TIMELINE',
                style: TextStyle(
                  color: Colors.white60,
                  fontSize: 12,
                  fontWeight: FontWeight.w800,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 10),
              _buildTimelineView(),
              const SizedBox(height: 20),
            ],

            // Actionable Safety Recommendations with Interactive Checkboxes
            if (widget.analysis.recommendations.isNotEmpty) ...[
              const Text(
                'RECOMMENDED ACTIONS (CHECKLIST)',
                style: TextStyle(
                  color: Colors.white60,
                  fontSize: 12,
                  fontWeight: FontWeight.w800,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 8),
              _buildRecommendationsCard(),
              const SizedBox(height: 20),
            ],

            // Full Speech Transcript
            if (widget.analysis.transcript.isNotEmpty) ...[
              const Text(
                'FLAGGED SPEECH TRANSCRIPT',
                style: TextStyle(
                  color: Colors.white60,
                  fontSize: 12,
                  fontWeight: FontWeight.w800,
                  letterSpacing: 1.2,
                ),
              ),
              const SizedBox(height: 8),
              _buildTranscriptCard(),
              const SizedBox(height: 24),
            ],

            // Action buttons: Report Scam / Return
            _buildBottomButtons(context),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildCallHeaderCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFF1E293B),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF334155)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: widget.analysis.level.color.withValues(alpha: 0.15),
              shape: BoxShape.circle,
            ),
            child: Icon(widget.analysis.level.icon, color: widget.analysis.level.color, size: 24),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  widget.analysis.callerName,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w800,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  widget.analysis.callerNumber,
                  style: const TextStyle(color: Colors.white60, fontSize: 13),
                ),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFF0F172A),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Text(
                  '⏱ ${_formatDuration(widget.analysis.callDurationSeconds)}',
                  style: const TextStyle(
                    color: Colors.white70,
                    fontSize: 11,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              const SizedBox(height: 4),
              Text(
                '${widget.analysis.analyzedAt.hour.toString().padLeft(2, '0')}:${widget.analysis.analyzedAt.minute.toString().padLeft(2, '0')}',
                style: const TextStyle(color: Colors.white38, fontSize: 11),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTimelineView() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFF131B2E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF1E293B)),
      ),
      child: Column(
        children: widget.analysis.timeline.asMap().entries.map((entry) {
          final idx = entry.key;
          final item = entry.value;
          final isLast = idx == widget.analysis.timeline.length - 1;

          return IntrinsicHeight(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Timeline marker line
                Column(
                  children: [
                    Container(
                      width: 12,
                      height: 12,
                      decoration: BoxDecoration(
                        color: item.level.color,
                        shape: BoxShape.circle,
                        border: Border.all(color: Colors.white, width: 2),
                      ),
                    ),
                    if (!isLast)
                      Expanded(
                        child: Container(
                          width: 2,
                          color: const Color(0xFF334155),
                        ),
                      ),
                  ],
                ),
                const SizedBox(width: 12),

                // Content
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.only(bottom: 16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              item.flagReason,
                              style: const TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.w700,
                                fontSize: 13,
                              ),
                            ),
                            Text(
                              '${item.timeFormatted} (${item.score}%)',
                              style: TextStyle(
                                color: item.level.color,
                                fontWeight: FontWeight.bold,
                                fontSize: 11,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 4),
                        Text(
                          '"${item.transcriptSnippet}"',
                          style: const TextStyle(
                            color: Colors.white70,
                            fontSize: 12,
                            fontStyle: FontStyle.italic,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildRecommendationsCard() {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFF131B2E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF334155)),
      ),
      child: Column(
        children: widget.analysis.recommendations.asMap().entries.map((entry) {
          final idx = entry.key;
          final rec = entry.value;
          final isChecked = _checkedRecommendations[idx];

          return InkWell(
            onTap: () {
              setState(() {
                _checkedRecommendations[idx] = !_checkedRecommendations[idx];
              });
            },
            borderRadius: BorderRadius.circular(8),
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 4),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    isChecked ? Icons.check_box_rounded : Icons.check_box_outline_blank_rounded,
                    color: isChecked ? const Color(0xFF10B981) : Colors.white38,
                    size: 20,
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      rec,
                      style: TextStyle(
                        color: isChecked ? Colors.white60 : Colors.white,
                        decoration: isChecked ? TextDecoration.lineThrough : null,
                        fontSize: 13,
                        height: 1.35,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildTranscriptCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFF131B2E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF334155)),
      ),
      child: Text(
        widget.analysis.transcript,
        style: const TextStyle(
          color: Colors.white70,
          fontSize: 13,
          height: 1.45,
        ),
      ),
    );
  }

  Widget _buildBottomButtons(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: OutlinedButton.icon(
            onPressed: _isReported ? null : _openReportNumberDialog,
            icon: Icon(
              _isReported ? Icons.verified_rounded : Icons.report_gmailerrorred_rounded,
              color: _isReported ? Colors.white38 : const Color(0xFFEF4444),
            ),
            label: Text(
              _isReported ? 'Reported ✓' : 'Report Number',
              style: TextStyle(
                color: _isReported ? Colors.white38 : const Color(0xFFEF4444),
                fontWeight: FontWeight.bold,
              ),
            ),
            style: OutlinedButton.styleFrom(
              side: BorderSide(color: _isReported ? Colors.white24 : const Color(0xFFEF4444)),
              padding: const EdgeInsets.symmetric(vertical: 14),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
            ),
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: ElevatedButton.icon(
            onPressed: () => Navigator.pop(context),
            icon: const Icon(Icons.done_all_rounded, color: Colors.white),
            label: const Text(
              'Done',
              style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
            ),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF2563EB),
              padding: const EdgeInsets.symmetric(vertical: 14),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
            ),
          ),
        ),
      ],
    );
  }
}
